/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=testing/run-authorization/wrangler.jsonc --include-runtime=false --env-interface=RunAuthorizationEnv testing/run-authorization/worker-configuration.d.ts` (hash: 1970b119a60b4175f30c2acbdb2863f1)
interface __BaseEnv_RunAuthorizationEnv {
	STAGING_TOKEN: string;
	SESSION: DurableObjectNamespace<import("./worker").AuthorizationSession>;
	AUTHORIZER: DurableObjectNamespace<import("./worker").ManualAuthorizer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "AuthorizationSession" | "ManualAuthorizer";
	}
	interface Env extends __BaseEnv_RunAuthorizationEnv {}
}
interface RunAuthorizationEnv extends __BaseEnv_RunAuthorizationEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STAGING_TOKEN">> {}
}
