/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=examples/celld/001-no-tools/wrangler.jsonc --env-file=examples/celld/001-no-tools/.dev.vars.example --include-runtime=false examples/celld/001-no-tools/worker-configuration.d.ts` (hash: e1b1759b9687942dbb977667f4d04afb)
interface __BaseEnv_Env {
	EDA_OPENAI_MODEL: "gpt-4.1-mini";
	EDA_SESSION: DurableObjectNamespace<import("./worker").CelldNoToolsSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "CelldNoToolsSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EDA_OPENAI_MODEL">> {}
}
